baseURL = "http://localhost:1313/"
languageCode = "ja-JA"
title = "Nanananananana's New Hugo Site"
description = "a Blog by Jeremiah Succeed"
config = "config.toml"
tags = ["blog", "sidebar", "SEO"]
theme = "onepress"
# Enter your tracking code to enable Google Analytics
googleAnalytics = " "
# Disable comments by leaving disqusShortname empty
disqusShortname = "your disqus shortname"
copyright = "Copyright © 2019, orerus Succeed; all rights reserved."
canonifyURLS = true
paginate = 12

[params]
	author = "orerus"
    bio = "TBD"
	logo = "/images/onepress-logo.png"
	avatar = "/images/onepress-author.png"
	opengraphImage = "/images/onepress-logo.jpg"
	enableRSS = true

	customCSS = false
    readMore = "Read Up"
    
    # Social
	twitter  = "https://twitter.com/orerus"
	github   = "https://github.com/orerus"
	facebook  = ""
    linkedin  = ""

    
    # Widget
    widgets = true
    
    # Author box and Share button
    authorCard = false 
    shareButton = true
    
    # Code highlighting with highlight.js
    highlightJS = true

# Taxonomies
[taxonomies]
    tag = "tags"