version: '3'
services:
  app:
    image: peaceiris/hugo:v0.85.0-full
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
    #entrypoint: sh
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    tty: true